spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/nakup-order
    username: postgres
    password: zxca
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: nakup-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
#            value:
#              default:
#                type: nakup.order.model.event.OrderFormedRequest
            use:
              type:
                headers: false
            trusted:
              packages: "*"
            use-type-headers: false
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    app-name: order-service
    instance-id: ${spring.application.name}:${random.value}

